---
- name: Customize a host
  hosts: localhost
  connection: local
  
  tasks:

    - name: set vi mode
      lineinfile:
        path: ~/.bashrc
        line: "set -o vi"

    - name: Start customizing vim
      blockinfile:
        path:     ~/.vimrc
        create:   yes
        block: |
          set tabstop=2
          set expandtab
